import json
import os
import pandas as pd
from src.solar_angle_calculations import calculate_angle
from src.radiation_calculation import calculate_radiation
from src.aoi_calculation import aoi_calculation
from src.perez_model import perez
from src.poa_calc import effective_poa_calculation
from src.power_dc import power_dc_calculation
from src.power_ac import power_ac_calculation
from src.util import *


def lambda_handler(event, context):
    name = event["name"]
    latitude = event["latitude"]
    longitude = event["longitude"]
    GMT = event["GMT"]
    orientation = event['orientation']
    tiltangle = event['tiltangle']
    lossfactortoggle = event['lossfactortoggle']
    pvefficiency = event['pvefficiency']
    panel_num = event['panel_num']
    area_per_panel = event['area_per_panel']
    invertsize = event['invertsize']
    invertefficiency = event['invertefficiency']
    sys_losses = {
        'soiling': 0.02,
        'shading': 0.03,
        'snow': 0.0,
        'mismatch': 0.02,
        'wiring': 0.02,
        'connections': 0.005,
        'lid': 0.015,
        'nameplate': 0.01,
        'age': 0.0,
        'availability': 0.02,
    }
    if 'sys_losses' in event.keys():
        sys_losses = event['sys_losses']

    # bucket = event['bucket']
    # key = event['key']
    # file_path = s3_path.format(bucket, key)
    file_path = 'sites/{}.csv'.format(name)
    # file_path = 'Solar PV Model Rev1.6.xlsx'
    print(file_path)
    df = pd.read_csv(file_path, parse_dates=['TimeStamp'])
    # print(df)
    # calculate solar angle
    df = calculate_angle(df, latitude, longitude, GMT)

    # normalize solar radiation data
    df = calculate_radiation(df)

    # calculate angle of incidence (AOI)
    df = aoi_calculation(df, orientation, tiltangle)

    # run perez model
    df = perez(df, tiltangle)

    # calculate effective poa
    df = effective_poa_calculation(df, tiltangle)

    # calculate power DC
    df = power_dc_calculation(df, lossfactortoggle, pvefficiency, sys_losses, panel_num,
                              area_per_panel)

    # calculate final power AC
    df = power_ac_calculation(df, invertsize, invertefficiency)

    # output
    local_path = '{}_generation.csv'.format(name)
    df.to_csv(f'generation/{local_path}', index=False)
    # print(put_file_to_s3(f'/tmp/{local_path}', bucket, local_path))

    return {
        'statusCode': 200,
        'body': json.dumps('Calculation finished.')
    }


if __name__ == '__main__':
    sites_list = [
        {
            'name': 'Florence Street',
            'latitude': -34.950559,
            'longitude': 138.6315199,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Linsell Lodge Hostel',
            'latitude': -34.854044,
            'longitude': 138.5601117,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Gawler Corps',
            'latitude': -34.5938013,
            'longitude': 138.7506146,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Bethesda Aged Care Plus',
            'latitude': -23.3765787,
            'longitude': 150.496089,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Nambour Family Stores',
            'latitude': -26.6290245,
            'longitude': 152.9596877,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Shaftesbury Court Retirement Village',
            'latitude': -33.8771099,
            'longitude': 151.1071456,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Northside Hornsby Gateway Corps',
            'latitude': -33.702806,
            'longitude': 151.104954,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Eastlake Corps',
            'latitude': -33.0219905,
            'longitude': 151.6655771,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Elizabeth Jenkins Place Aged Care Plus',
            'latitude': -33.7344586,
            'longitude': 151.2998209,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Newcastle Worship and Community Centre',
            'latitude': -32.9204889,
            'longitude': 151.7452094,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Wollongong Corps',
            'latitude': -34.4260521,
            'longitude': 150.8909451,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Family Services Management',
            'latitude': -37.757305,
            'longitude': 144.964003,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'James Barker House',
            'latitude': -37.803934,
            'longitude': 144.8998859,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Abbotsford Salvos Stores',
            'latitude': -37.805749,
            'longitude': 144.998192,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Mundy Street',
            'latitude': -36.7636383,
            'longitude': 144.2920565,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'SalvoConnect',
            'latitude': -38.1549769,
            'longitude': 144.3717657,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Victoria Division - Ballarat Office',
            'latitude': -37.5671694,
            'longitude': 143.869179334406,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Eva Burrows College',
            'latitude': -37.8294426,
            'longitude': 145.2246585,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Ringwood Corps',
            'latitude': -37.8327474,
            'longitude': 145.2272779,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Moyne Aged Care',
            'latitude': -33.170972,
            'longitude': 148.210149,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Shared Services Group',
            'latitude': -33.8471781,
            'longitude': 151.0309248,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Mary Street',
            'latitude': -33.8812971,
            'longitude': 151.2101542,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Stafford Corps',
            'latitude': -27.41511905,
            'longitude': 153.0127254,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Life Community Church',
            'latitude': -27.6392755,
            'longitude': 153.1370244,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
        {
            'name': 'Towards Independence',
            'latitude': -34.9302731,
            'longitude': 138.5940005,
            'GMT': 11,
            'orientation': 0,
            'tiltangle': 25,
            'lossfactortoggle': 1,
            'pvefficiency': 0.1888,
            'panel_num': 5,
            'area_per_panel': 1.29797538461538,
            'invertsize': 1.04,
            'invertefficiency': 0.96,
            'sys_losses': {
                'soiling': 0.02,
                'shading': 0.03,
                'snow': 0.0,
                'mismatch': 0.02,
                'wiring': 0.02,
                'connections': 0.005,
                'lid': 0.015,
                'nameplate': 0.01,
                'age': 0.0,
                'availability': 0.02,
            },
        },
    ]

    i = 0
    for site in sites_list:
        i += 1
        print('No.' + str(i) + ': ' + site['name'] + ' has started')
        lambda_handler(site, None)
        print('No.' + str(i) + ': ' + site['name'] + ' has ended\n')
